name: JCoreBukkit
main: dev.jaims.jcore.bukkit.JCore
version: @version@
author: Jaimss
depend: [ PlaceholderAPI ]

commands:
  gma:
    aliases: [ gamemodeadventure ]
    description: "Set your or a target's gamemode to adventure."
  gmc:
    aliases: [ gamemodecreative ]
    description: "Set your or a target's gamemode to creative."
  gmsp:
    aliases: [ gamemodespectator ]
    description: "Set your or a target's gamemode to spectator."
  gms:
    aliases: [ gamemodesurvival ]
    description: "Set your or a target's gamemode to survival."
  clear:
    aliases: [ ci,clearinventory ]
    description: "Clear your or a target's inventory."
  dispose:
    aliases: [ disposal,trash ]
    description: "Get rid of extra items."
  feed:
    description: "Feed yourself or a target."
  fly:
    description: "Enable flight for yourself or a target."
  give:
    aliases: [ i,giveitem ]
    description: "Give an item to yourself or a target."
  heal:
    description: "Heal yourself or a target."
  help:
    description: "Show help pages."
  jcorereload:
    description: "Reload JCore and all of its files"

permissions:
  # admin perms
  jcore.admin:
    default: op
    description: Access to everything.
  # commands
  jcore.command.*:
    default: false
    children:
      jcore.command.runwithsigns: true
      jcore.command.gamemode.*:
        default: false
        children:
          jcore.command.gamemode.survival: true
          jcore.command.gamemode.creative: true
          jcore.command.gamemode.adventure: true
          jcore.command.gamemode.spectator: true
          jcore.command.gamemode.survival.others: true
          jcore.command.gamemode.creative.others: true
          jcore.command.gamemode.adventure.others: true
          jcore.command.gamemode.spectator.others: true
      jcore.command.clear.*:
        default: false
        children:
          jcore.command.clear: true
          jcore.command.clear.others: true
      jcore.command.dispose: true
      jcore.command.feed.*:
        default: false
        children:
          jcore.command.feed: true
          jcore.command.feed.others: true
      jcore.command.fly.*:
        default: false
        children:
          jcore.command.fly: true
          jcore.command.fly.others: true
      jcore.command.give.*:
        default: false
        children:
          jcore.command.give: true
          jcore.command.give.others: true
      jcore.command.heal.*:
        default: false
        children:
          jcore.command.heal: true
          jcore.command.heal.others: true
      jcore.command.reload:
        default: false
  # chat perms
  jcore.chat.*:
    default: false
    children:
      jcore.chat.defaultcolor: true
      jcore.chat.markdown.*:
        default: false
        children:
          jcore.chat.markdown.bold: true
          jcore.chat.markdown.italic: true
          jcore.chat.markdown.strikethrough: true
          jcore.chat.markdown.underline: true
          jcore.chat.markdown.obfuscated: true
          jcore.chat.markdown.color: true
          jcore.chat.markdown.hex: true
          jcore.chat.markdown.gradient: true
          jcore.chat.markdown.rainbow: true
          jcore.chat.markdown.actions: true
      jcore.chat.color.*:
        default: false
        children:
          jcore.chat.color.purple: true
          jcore.chat.color.magenta: true
          jcore.chat.color.pink: true
          jcore.chat.color.cyan: true
          jcore.chat.color.lightblue: true
          jcore.chat.color.blue: true
          jcore.chat.color.lime: true
          jcore.chat.color.green: true
          jcore.chat.color.red: true
          jcore.chat.color.orange: true
          jcore.chat.color.yellow: true
          jcore.chat.color.brown: true
          jcore.chat.color.lightgray: true
          jcore.chat.color.gray: true
          jcore.chat.color.black: true
          jcore.chat.color.white: true