name: JCoreBukkit
main: dev.jaims.jcore.bukkit.JCore
version: @version@
author: Jaimss
depend:
  - PlaceholderAPI

commands:
  # gamemode section
  gma:
    aliases:
      - gamemodeadventure
    description: ""
  gmc:
    aliases:
      - gamemodecreative
    description: ""
  gmsp:
    aliases:
      - gamemodespectator
    description: ""
  gms:
    aliases:
      - gamemodesurvival
    description: ""

  clear:
    aliases:
      - ci
      - clearinventory
    description: ""
  feed:
    description: ""
  fly:
    description: ""
  give:
    aliases:
      - i
      - giveitem
    description: ""
  heal:
    description: ""
  help:
    description: ""