name: JCoreBukkit
main: dev.jaims.jcore.bukkit.JCore
version: @version@
author: Jaimss
depend:
  - PlaceholderAPI

commands:
  clear:
    aliases:
      - ci
      - clearinventory
    description: ""
  feed:
    description: ""
  fly:
    description: ""
  give:
    aliases:
      - i
      - giveitem
    description: ""
  heal:
    description: ""
  help:
    description: ""