name: JCoreBukkit
main: dev.jaims.jcore.bukkit.JCore
version: @version@
author: Jaimss
depend: [ PlaceholderAPI, Vault ]
description: "A Modular and Customizable Core Plugin"

commands:
  gma:
    aliases: [ gamemodeadventure ]
    description: "Set your or a target's gamemode to adventure."
  gmc:
    aliases: [ gamemodecreative ]
    description: "Set your or a target's gamemode to creative."
  gmsp:
    aliases: [ gamemodespectator ]
    description: "Set your or a target's gamemode to spectator."
  gms:
    aliases: [ gamemodesurvival ]
    description: "Set your or a target's gamemode to survival."
  nickname:
    aliases: [ nick ]
    description: "Set your nickname"
  unnick:
    description: "Unset your nickname"
  repair:
    description: "Repair items"
  repairall:
    description: "Repair all items"
  flyspeed:
    description: "Change your flyspeed"
  speed:
    description: "Change the speed of you if you are flying/walking"
  walkspeed:
    description: "Change your walkspeed"
  clear:
    aliases: [ ci,clearinventory ]
    description: "Clear your or a target's inventory."
  dispose:
    aliases: [ disposal,trash ]
    description: "Get rid of extra items."
  feed:
    description: "Feed yourself or a target."
  fly:
    description: "Enable flight for yourself or a target."
  give:
    aliases: [ i,giveitem ]
    description: "Give an item to yourself or a target."
  heal:
    description: "Heal yourself or a target."
  help:
    description: "Show help pages."
  jcorereload:
    description: "Reload JCore and all of its files"

permissions:
  # admin perms
  jcore.admin:
    default: op
    description: "Access to everything"
  ########################
  ### COMMANDS SECTION ###
  ########################
  jcore.command.silent:
    default: op
  jcore.command.runwithsigns:
    default: op
  # gamemode commands
  jcore.command.gamemode.survival:
    default: op
  jcore.command.gamemode.creative:
    default: op
  jcore.command.gamemode.adventure:
    default: op
  jcore.command.gamemode.spectator:
    default: op
  jcore.command.gamemode.survival.others:
    default: op
  jcore.command.gamemode.creative.others:
    default: op
  jcore.command.gamemode.adventure.others:
    default: op
  jcore.command.gamemode.spectator.others:
    default: op
  # nick
  jcore.command.nickname:
    default: op
  jcore.command.nickname.others:
    default: op
  jcore.command.unnick:
    default: op
  jcore.command.unnick.others:
    default: op
  # repair
  jcore.command.repair:
    default: op
  jcore.command.repair.others:
    default: op
  jcore.command.repairall:
    default: op
  jcore.command.rapairall.others:
    default: op
  # speed
  jcore.command.flyspeed:
    default: op
  jcore.command.flyspeed.others:
    default: op
  jcore.command.walkspeed:
    default: op
  jcore.command.walkspeed.others:
    default: op
  # clear
  jcore.command.clear:
    default: op
  jcore.command.clear.others:
    default: op
  # dispose
  jcore.command.dispose:
    default: op
  # feed
  jcore.command.feed:
    default: op
  jcore.command.feed.others:
    default: op
  # fly
  jcore.command.fly:
    default: op
  jcore.command.fly.others:
    default: op
  # give
  jcore.command.give:
    default: op
  jcore.command.give.others:
    default: op
  # heal
  jcore.command.heal:
    default: op
  jcore.command.heal.others:
    default: op
  # reload
  jcore.command.reload:
    default: op
  ####################
  ### CHAT SECTION ###
  ####################
  # markdown
  jcore.chat.markdown.bold:
    default: op
  jcore.chat.markdown.italic:
    default: op
  jcore.chat.markdown.strikethrough:
    default: op
  jcore.chat.markdown.underline:
    default: op
  jcore.chat.markdown.obfuscated:
    default: op
  jcore.chat.markdown.color:
    default: op
  jcore.chat.markdown.hex:
    default: op
  jcore.chat.markdown.gradient:
    default: op
  jcore.chat.markdown.rainbow:
    default: op
  jcore.chat.markdown.actions:
    default: op
  # set a default chat color
  jcore.chat.defaultcolor:
    default: op
  # access to different colors
  jcore.chat.color.purple:
    default: op
  jcore.chat.color.magenta:
    default: op
  jcore.chat.color.pink:
    default: op
  jcore.chat.color.cyan:
    default: op
  jcore.chat.color.lightblue:
    default: op
  jcore.chat.color.blue:
    default: op
  jcore.chat.color.lime:
    default: op
  jcore.chat.color.green:
    default: op
  jcore.chat.color.red:
    default: op
  jcore.chat.color.orange:
    default: op
  jcore.chat.color.yellow:
    default: op
  jcore.chat.color.brown:
    default: op
  jcore.chat.color.lightgray:
    default: op
  jcore.chat.color.gray:
    default: op
  jcore.chat.color.black:
    default: op
  jcore.chat.color.white:
    default: op